CC=gcc
HARDORE=-pthread -pedantic -ansi -Wall -Werror -pthread
CFILES=./src/main.c


all:
		$(CC) $(CFILES) $(HARDCORE) -o order

debug:
		$(CC) -g -pthread $(CFILES)  $(CFLAGS) -o order

clean:
		rm order
